---

  - name: Add the elasticsearch yum repository
    template:
        dest: "{{ elasticsearch_yum_repo_template_dest }}" # required. Location to render the template to on the remote machine.
        src: "{{ elasticsearch_yum_repo_template_file }}" # required. Path of a Jinja2 formatted template on the Ansible controller. This can be a relative or absolute path.
        owner: root # not required. Name of the user that should own the file/directory, as would be fed to I(chown).
        group: root # not required. Name of the group that should own the file/directory, as would be fed to I(chown).
    when: elasticsearch_repo|bool

  - name: Add the elasticsearch yum repository with yum repo
    yum_repository:
        name: "{{ elasticsearch_yum_repo_name }}" # required. Unique repository ID. This option builds the section name of the repository in the repo file.,This parameter is only required if I(state) is set to C(present) or C(absent).
        enabled: yes # not required. This tells yum whether or not use this repository.
        owner: root # not required. Name of the user that should own the file/directory, as would be fed to I(chown).
        repo_gpgcheck: no # not required. This tells yum whether or not it should perform a GPG signature check on the repodata from this repository.
        sslverify: yes # not required. Defines whether yum should verify SSL certificates/hosts at all.
        gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch" # not required. A URL pointing to the ASCII-armored GPG key file for the repository.,It can also be a list of multiple URLs.
        state: present # not required. choices: absent;present. State of the repo file.
        gpgcheck: "yes"
        description: "Elasticsearch Repository"
        baseurl: "https://artifacts.elastic.co/packages/7.x/yum"
        group: "root"
        async: yes # not required. If set to C(yes) Yum will download packages and metadata from this repo in parallel, if possible.
    when: elasticsearch_yum_repo|bool

  - name: Install elasticsearch
    yum:
      name: "{{ elasticsearch_yum_name }}"
      state: installed
    notify: start and enable elasticsearch