---
# tasks file for automate_beats

  - name: Install all the Beats
    include_tasks: install_all.yml
    when: install_all_beats
    
  - name: Install Filebeat
    include_tasks: filebeat.yml
    when: filebeat

  - name: Install Metricbeat
    include_tasks: metricbeat.yml
    when: metricbeat

  - name: Install Packetbeat
    include_tasks: metricbeat.yml
    when: packetbeat
    
  - name: Install Auditbeat.yml
    include_tasks: auditbeat.yml
    when: auditbeat