---

  - name: Install metricbeat
    yum:
      name: "{{ metricbeat_rpm }}"
      state: installed
    

  - name: Configure Metricbeat
    template:
        dest: "{{ metricbeat_dest }}" # required. Location to render the template to on the remote machine.
        src:  "{{ metricbeat_src }}" # required. Path of a Jinja2 formatted template on the Ansible controller. This can be a relative or absolute path.
        owner: metricbeat # not required. Name of the user that should own the file/directory, as would be fed to I(chown).
        group: metricbeat # not required. Name of the group that should own the file/directory, as would be fed to I(chown).
    notify: start and enable metricbeat